name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'gradle/pom.versions.toml'
      - 'build.gradle.kts'
      - 'mustbe-*/build.gradle.kts'

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      should-release: ${{ steps.check.outputs.should-release }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if version changed
        id: check
        run: |
          # Получаем текущую версию из TOML
          CURRENT_VERSION=$(grep 'projectVersion =' gradle/pom.versions.toml | cut -d'"' -f2)
          echo "Current version: $CURRENT_VERSION"
          
          # Получаем последний тег
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          LATEST_VERSION=${LATEST_TAG#v}
          echo "Latest tag version: $LATEST_VERSION"
          
          # Сравниваем версии
          if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
            echo "should-release=true" >> $GITHUB_OUTPUT
            echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
            echo "Version changed from $LATEST_VERSION to $CURRENT_VERSION"
          else
            echo "should-release=false" >> $GITHUB_OUTPUT
            echo "version=" >> $GITHUB_OUTPUT
            echo "No version change detected"
          fi

  release:
    needs: check-version
    if: needs.check-version.outputs.should-release == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build and Publish
        env:
          MAVEN_CENTRAL_USERNAME: ${{ env.OSSRH_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ env.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ env.GPG_KEY_ID }}
          SIGNING_PASSWORD: ${{ env.GPG_PASSPHRASE }}
          SIGNING_SECRET_KEY: ${{ env.GPG_PRIVATE_KEY }}
        run: |
          echo "$SIGNING_SECRET_KEY" > mustbe_private.asc
          ./gradlew publishToMavenCentral

      - name: Create Git Tag
        run: |
          VERSION="${{ needs.check-version.outputs.version }}"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ env.TOKEN_GITHUB }}
        with:
          tag_name: v${{ needs.check-version.outputs.version }}
          release_name: Release v${{ needs.check-version.outputs.version }}
          body: |
            ## What's Changed
            
            This release includes the latest updates to MustBe KSP validation library.
            
            ### Artifacts
            
            - `com.suleimanov.kotlin:mustbe-annotations:v${{ needs.check-version.outputs.version }}`
            - `com.suleimanov.kotlin:mustbe-processor:v${{ needs.check-version.outputs.version }}`
            
            ### Usage
            
            ```kotlin
            plugins {
                id("com.google.devtools.ksp") version "2.0.20-1.0.24"
            }
            
            dependencies {
                implementation("com.suleimanov.kotlin:mustbe-annotations:v${{ needs.check-version.outputs.version }}")
                ksp("com.suleimanov.kotlin:mustbe-processor:v${{ needs.check-version.outputs.version }}")
            }
            ```
          draft: false
          prerelease: false 